#task5_1
MEHV29/.NET-Course pull request #6
Opened 2023-11-28 02:11 UTC by MEHV29

This contains the point 5.1 of the thask

2023-12-01 11:00 UTC, IgorKheidorov requested changes
Fix issues with indexer))

2023-12-01 11:00 UTC, IgorKheidorov commented on Task5/Task5_1/SparseMatrix.cs
> +
Why exception? maybe I want just to change value of element? Fix

2023-12-01 11:00 UTC, IgorKheidorov commented on Task5/Task5_1/SparseMatrix.cs
> +
What about if the element is not found? You has to return 0

2023-12-01 11:00 UTC, IgorKheidorov commented on Task5/Task5_1/SparseMatrix.cs
> +﻿using System;
Remove unused usings

2023-12-01 22:17 UTC, MEHV29 commented on Task5/Task5_1/SparseMatrix.cs
> +
Fixed

2023-12-01 22:17 UTC, MEHV29 commented on Task5/Task5_1/SparseMatrix.cs
> +﻿using System;
Modified

2023-12-01 22:20 UTC, MEHV29 commented on Task5/Task5_1/SparseMatrix.cs
> +
I hadn't added it because by default the method Find returns the default value for the type if not found the item but its already added.

2023-12-06 10:32 UTC, IgorKheidorov approved these changes

2023-12-07 16:20 UTC, merged